/** Embedded tile set data (no server needed) */
export const TILE_DATA = {
  tileSets: [
    {
      name: "Vowels", category: "vowel", tiles: [
        { id: "vowel-a", grapheme: "a", category: "vowel", color: "#2196F3" },
        { id: "vowel-e", grapheme: "e", category: "vowel", color: "#2196F3" },
        { id: "vowel-i", grapheme: "i", category: "vowel", color: "#2196F3" },
        { id: "vowel-o", grapheme: "o", category: "vowel", color: "#2196F3" },
        { id: "vowel-u", grapheme: "u", category: "vowel", color: "#2196F3" },
      ]
    },
    {
      name: "Consonants", category: "consonant", tiles: [
        { id: "con-b", grapheme: "b", category: "consonant", color: "#FFC107" },
        { id: "con-c", grapheme: "c", category: "consonant", color: "#FFC107" },
        { id: "con-d", grapheme: "d", category: "consonant", color: "#FFC107" },
        { id: "con-f", grapheme: "f", category: "consonant", color: "#FFC107" },
        { id: "con-g", grapheme: "g", category: "consonant", color: "#FFC107" },
        { id: "con-h", grapheme: "h", category: "consonant", color: "#FFC107" },
        { id: "con-j", grapheme: "j", category: "consonant", color: "#FFC107" },
        { id: "con-k", grapheme: "k", category: "consonant", color: "#FFC107" },
        { id: "con-l", grapheme: "l", category: "consonant", color: "#FFC107" },
        { id: "con-m", grapheme: "m", category: "consonant", color: "#FFC107" },
        { id: "con-n", grapheme: "n", category: "consonant", color: "#FFC107" },
        { id: "con-p", grapheme: "p", category: "consonant", color: "#FFC107" },
        { id: "con-q", grapheme: "q", category: "consonant", color: "#FFC107" },
        { id: "con-r", grapheme: "r", category: "consonant", color: "#FFC107" },
        { id: "con-s", grapheme: "s", category: "consonant", color: "#FFC107" },
        { id: "con-t", grapheme: "t", category: "consonant", color: "#FFC107" },
        { id: "con-v", grapheme: "v", category: "consonant", color: "#FFC107" },
        { id: "con-w", grapheme: "w", category: "consonant", color: "#FFC107" },
        { id: "con-x", grapheme: "x", category: "consonant", color: "#FFC107" },
        { id: "con-y", grapheme: "y", category: "consonant", color: "#FFC107" },
        { id: "con-z", grapheme: "z", category: "consonant", color: "#FFC107" },
      ]
    },
    {
      name: "Digraphs", category: "digraph", tiles: [
        { id: "di-sh", grapheme: "sh", category: "digraph", color: "#E91E8C" },
        { id: "di-ch", grapheme: "ch", category: "digraph", color: "#E91E8C" },
        { id: "di-th", grapheme: "th", category: "digraph", color: "#E91E8C" },
        { id: "di-wh", grapheme: "wh", category: "digraph", color: "#E91E8C" },
        { id: "di-ph", grapheme: "ph", category: "digraph", color: "#E91E8C" },
        { id: "di-ck", grapheme: "ck", category: "digraph", color: "#E91E8C" },
        { id: "di-ng", grapheme: "ng", category: "digraph", color: "#E91E8C" },
        { id: "di-qu", grapheme: "qu", category: "digraph", color: "#E91E8C" },
        { id: "di-kn", grapheme: "kn", category: "digraph", color: "#E91E8C" },
        { id: "di-wr", grapheme: "wr", category: "digraph", color: "#E91E8C" },
        { id: "di-gn", grapheme: "gn", category: "digraph", color: "#E91E8C" },
      ]
    },
    {
      name: "Vowel Digraphs", category: "vowel-digraph", tiles: [
        { id: "vd-ai", grapheme: "ai", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ay", grapheme: "ay", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ee", grapheme: "ee", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ea", grapheme: "ea", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-oa", grapheme: "oa", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-oo", grapheme: "oo", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ou", grapheme: "ou", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ow", grapheme: "ow", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ie", grapheme: "ie", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ei", grapheme: "ei", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ue", grapheme: "ue", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ui", grapheme: "ui", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-ew", grapheme: "ew", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-au", grapheme: "au", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-aw", grapheme: "aw", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-oi", grapheme: "oi", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-oy", grapheme: "oy", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
        { id: "vd-oe", grapheme: "oe", category: "digraph", color: "#009688", subcategory: "vowel-digraph" },
      ]
    },
    {
      name: "Trigraphs", category: "trigraph", tiles: [
        { id: "tri-tch", grapheme: "tch", category: "trigraph", color: "#9C27B0" },
        { id: "tri-igh", grapheme: "igh", category: "trigraph", color: "#9C27B0" },
        { id: "tri-dge", grapheme: "dge", category: "trigraph", color: "#9C27B0" },
        { id: "tri-sch", grapheme: "sch", category: "trigraph", color: "#9C27B0" },
        { id: "tri-scr", grapheme: "scr", category: "trigraph", color: "#9C27B0" },
        { id: "tri-str", grapheme: "str", category: "trigraph", color: "#9C27B0" },
        { id: "tri-spr", grapheme: "spr", category: "trigraph", color: "#9C27B0" },
        { id: "tri-spl", grapheme: "spl", category: "trigraph", color: "#9C27B0" },
        { id: "tri-squ", grapheme: "squ", category: "trigraph", color: "#9C27B0" },
        { id: "tri-ear", grapheme: "ear", category: "trigraph", color: "#9C27B0" },
        { id: "tri-air", grapheme: "air", category: "trigraph", color: "#9C27B0" },
        { id: "tri-are", grapheme: "are", category: "trigraph", color: "#9C27B0" },
        { id: "tri-ore", grapheme: "ore", category: "trigraph", color: "#9C27B0" },
        { id: "tri-ure", grapheme: "ure", category: "trigraph", color: "#9C27B0" },
      ]
    },
    {
      name: "Blends", category: "blend", tiles: [
        { id: "bl-bl", grapheme: "bl", category: "blend", color: "#FF5722" },
        { id: "bl-br", grapheme: "br", category: "blend", color: "#FF5722" },
        { id: "bl-cl", grapheme: "cl", category: "blend", color: "#FF5722" },
        { id: "bl-cr", grapheme: "cr", category: "blend", color: "#FF5722" },
        { id: "bl-dr", grapheme: "dr", category: "blend", color: "#FF5722" },
        { id: "bl-fl", grapheme: "fl", category: "blend", color: "#FF5722" },
        { id: "bl-fr", grapheme: "fr", category: "blend", color: "#FF5722" },
        { id: "bl-gl", grapheme: "gl", category: "blend", color: "#FF5722" },
        { id: "bl-gr", grapheme: "gr", category: "blend", color: "#FF5722" },
        { id: "bl-pl", grapheme: "pl", category: "blend", color: "#FF5722" },
        { id: "bl-pr", grapheme: "pr", category: "blend", color: "#FF5722" },
        { id: "bl-sc", grapheme: "sc", category: "blend", color: "#FF5722" },
        { id: "bl-sk", grapheme: "sk", category: "blend", color: "#FF5722" },
        { id: "bl-sl", grapheme: "sl", category: "blend", color: "#FF5722" },
        { id: "bl-sm", grapheme: "sm", category: "blend", color: "#FF5722" },
        { id: "bl-sn", grapheme: "sn", category: "blend", color: "#FF5722" },
        { id: "bl-sp", grapheme: "sp", category: "blend", color: "#FF5722" },
        { id: "bl-st", grapheme: "st", category: "blend", color: "#FF5722" },
        { id: "bl-sw", grapheme: "sw", category: "blend", color: "#FF5722" },
        { id: "bl-tr", grapheme: "tr", category: "blend", color: "#FF5722" },
        { id: "bl-tw", grapheme: "tw", category: "blend", color: "#FF5722" },
        { id: "bl-ft", grapheme: "ft", category: "blend", color: "#FF5722" },
        { id: "bl-lt", grapheme: "lt", category: "blend", color: "#FF5722" },
        { id: "bl-nt", grapheme: "nt", category: "blend", color: "#FF5722" },
        { id: "bl-mp", grapheme: "mp", category: "blend", color: "#FF5722" },
        { id: "bl-nd", grapheme: "nd", category: "blend", color: "#FF5722" },
        { id: "bl-nk", grapheme: "nk", category: "blend", color: "#FF5722" },
        { id: "bl-lk", grapheme: "lk", category: "blend", color: "#FF5722" },
        { id: "bl-lp", grapheme: "lp", category: "blend", color: "#FF5722" },
        { id: "bl-lf", grapheme: "lf", category: "blend", color: "#FF5722" },
        { id: "bl-lm", grapheme: "lm", category: "blend", color: "#FF5722" },
        { id: "bl-pt", grapheme: "pt", category: "blend", color: "#FF5722" },
        { id: "bl-ct", grapheme: "ct", category: "blend", color: "#FF5722" },
      ]
    },
    {
      name: "Affixes", category: "affix", tiles: [
        { id: "af-pre", grapheme: "pre-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-un", grapheme: "un-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-re", grapheme: "re-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-dis", grapheme: "dis-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-mis", grapheme: "mis-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-over", grapheme: "over-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-out", grapheme: "out-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-sub", grapheme: "sub-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-super", grapheme: "super-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-inter", grapheme: "inter-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-mid", grapheme: "mid-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-non", grapheme: "non-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-anti", grapheme: "anti-", category: "affix", color: "#C62828", subcategory: "prefix" },
        { id: "af-ing", grapheme: "-ing", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ed", grapheme: "-ed", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-er", grapheme: "-er", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-est", grapheme: "-est", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ly", grapheme: "-ly", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-tion", grapheme: "-tion", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ness", grapheme: "-ness", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ful", grapheme: "-ful", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-less", grapheme: "-less", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ment", grapheme: "-ment", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-able", grapheme: "-able", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ible", grapheme: "-ible", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ous", grapheme: "-ous", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ive", grapheme: "-ive", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-al", grapheme: "-al", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ic", grapheme: "-ic", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ity", grapheme: "-ity", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ize", grapheme: "-ize", category: "affix", color: "#C62828", subcategory: "suffix" },
        { id: "af-ise", grapheme: "-ise", category: "affix", color: "#C62828", subcategory: "suffix" },
      ]
    },
    {
      name: "Punctuation", category: "punctuation", tiles: [
        { id: "punc-dot", grapheme: ".", category: "punctuation", color: "#607D8B" },
        { id: "punc-comma", grapheme: ",", category: "punctuation", color: "#607D8B" },
        { id: "punc-excl", grapheme: "!", category: "punctuation", color: "#607D8B" },
        { id: "punc-quest", grapheme: "?", category: "punctuation", color: "#607D8B" },
        { id: "punc-apos", grapheme: "'", category: "punctuation", color: "#607D8B" },
        { id: "punc-dash", grapheme: "-", category: "punctuation", color: "#607D8B" },
        { id: "punc-colon", grapheme: ":", category: "punctuation", color: "#607D8B" },
        { id: "punc-semi", grapheme: ";", category: "punctuation", color: "#607D8B" },
      ]
    }
  ]
};
